services:
  - type: web
    name: diet-frontend
    env: docker
    repo: https://github.com/Harshikeshpatel2004/DIET_RECOMMENDATION-_SYSTEM
    dockerfilePath: Streamlit_Frontend/Dockerfile
    buildFilter:
      paths:
        - Streamlit_Frontend/**
